version: '3.8'

services:
  postgres:
    image: postgres:15-alpine 
    container_name: olist_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: olist_db
    ports:
      - "5432:5432"
    volumes:
      # Automated execute the script to create schema (raw, staging, analytics)
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      # Data sustainability
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d olist_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: olist_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres

  dbt: 
    build: .
    container_name: dbt_pipeline
    volumes: 
      - .:/usr/app
      - ~/.dbt/profiles.yml:/root/.dbt/profiles.yml
    depends_on: 
      postgres:
        condition: service_healthy
    # Wait for the database to be ready, install the package, and build the project.
    command: >
      sh -c "uv run dbt deps &&  uv run dbt build"

volumes:
  postgres_data: